name: WordPress Docker + ZAP Security Scan

on:
  push:
    branches:
      - main

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Dockerized WordPress
        run: |
          docker compose up -d
          sleep 30  # wait for services to start

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: "http://localhost:8000"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: ZAP Scan Baseline Report
          fail_action: false
          allow_issue_writing: true
          artifact_name: zap_scan
          # ❌ DO NOT ADD `docker_name` (it causes the error)

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: |
            report_html.html
            report_md.md
            report_json.json

      - name: Shutdown Containers
        run: docker compose down
