name: WordPress Docker + ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Dockerized WordPress
        run: |
          docker compose up -d
          sleep 30

      - name: Pull and Run ZAP Baseline Scan via CLI
        run: |
          docker run --network host -v ${{ github.workspace }}:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:8000 \
            -r zap_report.html -w zap_warnings.md -J zap_report.json || true

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: |
            zap_report.html
            zap_warnings.md
            zap_report.json

      - name: Shut Down WordPress
        run: docker compose down
