name: Docker WordPress CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker containers
        run: |
          docker compose up -d
          sleep 30  # Wait for services to fully start

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: "http://localhost:8000"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: ZAP Scan Baseline Report
          fail_action: false
          allow_issue_writing: true
          artifact_name: zap_scan

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: |
            report_html.html
            report_md.md
            report_json.json

      - name: Tear down
        run: docker-compose down
